spring.datasource.url=jdbc:postgresql://localhost:5432/messenger
spring.datasource.username=postgres
spring.datasource.password=qwer1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=2000

spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false

#??? Spring Boot (hot reboot)
spring.servlet.multipart.max-file-size=104857600
spring.servlet.multipart.max-request-size=104857600
spring.servlet.multipart.enabled=true
server.tomcat.max-http-form-post-size=104857600

# app.base-url=https://messenger.com
app.base-url=
