db.url=jdbc:postgresql://localhost:5432/messenger
db.username=postgres
db.password=qwer1234
db.driver=org.postgresql.Driver
db.pool.maxSize=10
db.pool.minIdle=2
db.pool.idleTimeout=30000
db.pool.maxLifetime=1800000
